spec:
  template:
    spec:
      containers:
      - env:
        - name: GREETING_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: hello-world
              key: greeting.message
